name: Android CI

on:
  push:
    branches: [ "ci/cd", "master" ]
  pull_request:
    branches: [ "ci/cd", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
      - uses: actions/checkout@v3

        with:
          node-version: 20
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build app
        run: ./gradlew assemble